# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nickname', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personnick',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='personnick',
            name='created_user',
        ),
        migrations.RemoveField(
            model_name='personnick',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='personnick',
            name='person',
        ),
        migrations.RemoveField(
            model_name='personnick',
            name='user_hate',
        ),
        migrations.RemoveField(
            model_name='personnick',
            name='user_like',
        ),
        migrations.DeleteModel(
            name='PersonNick',
        ),
    ]
