# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nickname', '0002_auto_20170922_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nickname',
            name='nickname',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
