# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='category',
            field=models.CharField(blank=True, choices=[('TV', 'TV'), ('신문', '신문'), ('인터넷', '인터넷')], max_length=10),
        ),
        migrations.AlterField(
            model_name='media',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
