# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 00:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0013_auto_20170525_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.News')),
                ('personevent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.PersonEvent')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='eventnews',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='eventnews',
            name='created_user',
        ),
        migrations.RemoveField(
            model_name='eventnews',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventnews',
            name='news',
        ),
        migrations.DeleteModel(
            name='EventNews',
        ),
        migrations.AlterUniqueTogether(
            name='evidence',
            unique_together=set([('personevent', 'news')]),
        ),
    ]
