# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 13:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0015_auto_20170530_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='person_picture/%Y/%m/'),
        ),
    ]
