# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0016_auto_20170605_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='event',
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='출생년도'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nick_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='별칭'),
        ),
    ]
