# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 07:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0019_auto_20170812_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='user_like',
            field=models.ManyToManyField(blank=True, null=True, related_name='person_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
