# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 15:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0020_person_user_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='person_follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
