# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 15:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0021_person_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='person_follow', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='person',
            name='user_like',
            field=models.ManyToManyField(blank=True, related_name='person_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
