# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 06:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0023_auto_20170814_0546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('spouse', 'spouse'), ('parent', 'parent')], max_length=10)),
                ('ctype', models.CharField(choices=[('father', 'father'), ('mother', 'mother'), ('husband', 'husband'), ('wife', 'wife')], max_length=10)),
                ('other', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationothers', to='records.Person')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='records.Person')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together=set([('other', 'person'), ('person', 'other')]),
        ),
    ]
