# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0024_auto_20170903_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='ctype',
            field=models.CharField(choices=[('결혼', '결혼'), ('이혼', '이혼'), ('father', 'father'), ('mother', 'mother')], max_length=10),
        ),
    ]
