# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 05:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0025_auto_20170915_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='ctype',
            field=models.CharField(choices=[('결혼', '결혼'), ('이혼', '이혼'), ('아버지', '아버지'), ('어머니', '어머니')], max_length=10),
        ),
    ]
