# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0026_auto_20170919_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('M', '남'), ('F', '여')], default='M', max_length=1),
        ),
    ]
