# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0027_person_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='ctype',
            field=models.CharField(choices=[('결혼', '결혼'), ('이혼', '이혼'), ('아버지', '아버지'), ('어머니', '어머니'), ('아들', '아들'), ('딸', '딸')], max_length=10),
        ),
    ]
