# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0029_auto_20170922_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='nick_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='별칭'),
        ),
    ]
