# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0030_auto_20171013_0544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('tag',), 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AddField(
            model_name='news',
            name='events',
            field=models.ManyToManyField(blank=True, null=True, to='records.Event'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='ctype',
            field=models.CharField(choices=[('아내', '아내'), ('남편', '남편'), ('아버지', '아버지'), ('어머니', '어머니'), ('아들', '아들'), ('딸', '딸')], max_length=10),
        ),
    ]
