# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0031_auto_20171020_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='eventnews', to='records.Event'),
        ),
    ]
