# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20170606_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(upload_to='user_profile/%Y/%m/'),
        ),
    ]
