# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mistake', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(max_length=30, verbose_name='오류 명칭'),
        ),
        migrations.AlterField(
            model_name='report',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='뉴스 등록이 안 되는 URL'),
        ),
    ]
