# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_auto_20170514_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='pic_link',
        ),
        migrations.AddField(
            model_name='event',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
