# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_auto_20170514_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='happended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
