# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 05:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_event_happended_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='happended_at',
            new_name='happened_at',
        ),
    ]
