# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_auto_20170514_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='happened_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
