# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_auto_20170514_0533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='created_user',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='news',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='personevent',
        ),
        migrations.AddField(
            model_name='personevent',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.News'),
        ),
        migrations.DeleteModel(
            name='Evidence',
        ),
    ]
