# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0014_auto_20170529_0026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='birth',
            new_name='birth_year',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='behavior',
            new_name='event',
        ),
    ]
